# Generated by Django 4.1.2 on 2022-11-04 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_maker', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_address', models.CharField(default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('paid_for', models.IntegerField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.basket')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fur', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(blank=True, default='', upload_to='photos/%Y/%m/%d')),
                ('on_storage', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('color', models.CharField(default='', max_length=50)),
                ('weight', models.IntegerField(default=0)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.maker')),
            ],
            options={
                'verbose_name': 'мебель',
                'verbose_name_plural': 'мебель',
            },
        ),
        migrations.CreateModel(
            name='BasketContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.basket')),
                ('fur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.furniture')),
            ],
        ),
    ]
